// KB IVS11560 응답만으로 OHLCV 캔들과 거래량을 표시한다.
(() => {
  const $ = id => document.getElementById(id); const fmt = v => v == null ? '-' : Number(v).toLocaleString('ko-KR');
  let period='D', rows=[], chart, candles, volumes;
  function initChart(){chart=LightweightCharts.createChart($('kbChart'),termChartOptions({autoSize:true,rightPriceScale:{scaleMargins:{top:.08,bottom:.28}},timeScale:{rightOffset:4},localization:{locale:'ko-KR',priceFormatter:p=>fmt(p)}}));candles=chart.addCandlestickSeries({...termCandleColors(),priceFormat:{type:'price',precision:0,minMove:1}});volumes=chart.addHistogramSeries({priceFormat:{type:'volume'},priceScaleId:'volume'});chart.priceScale('volume').applyOptions({scaleMargins:{top:.78,bottom:0}});chart.subscribeCrosshairMove(p=>{if(!p.time)return;const c=rows.find(x=>x.time===p.time);if(c)$('legend').innerHTML=`<b>${$('symbol').value}</b> · ${c.time} · 시 <b>${fmt(c.open)}</b> · 고 <b>${fmt(c.high)}</b> · 저 <b>${fmt(c.low)}</b> · 종 <b>${fmt(c.close)}</b> · 거래량 <b>${fmt(c.volume)}</b>`})}
  function draw(){candles.setData(rows.map(c=>({time:c.time,open:c.open,high:c.high,low:c.low,close:c.close})));volumes.setData(rows.map(c=>({time:c.time,value:c.volume||0,color:termAlpha(c.close>=c.open?termColors().up:termColors().down,.35)})));chart.timeScale().fitContent();$('rowCount').textContent=`${rows.length}건`;$('candleRows').innerHTML=[...rows].reverse().map(c=>`<tr><td>${c.time}</td><td>${fmt(c.open)}</td><td>${fmt(c.high)}</td><td>${fmt(c.low)}</td><td>${fmt(c.close)}</td><td>${fmt(c.volume)}</td><td>${fmt(c.amount)}</td></tr>`).join('')}
  function message(text){$('message').textContent=text||'';$('message').style.display=text?'block':'none'}
  async function load(){const symbol=$('symbol').value.trim();if(!/^\d{6}$/.test(symbol)){message('종목코드는 6자리 숫자로 입력하세요.');return}$('load').disabled=true;message('');try{const params=new URLSearchParams({symbol,market:$('market').value,period,count:$('count').value});const response=await apiFetch(`/api/broker-test/kb/chart?${params}`);const body=await response.json();if(!response.ok||!body.ok)throw new Error(body.message||'KB 차트 조회에 실패했습니다.');rows=(body.result?.candles||[]).filter(c=>[c.open,c.high,c.low,c.close].every(Number.isFinite));if(!rows.length)throw new Error('KB API가 캔들 데이터를 반환하지 않았습니다. 종목과 시장을 확인하세요.');draw();$('legend').textContent=`${body.result.market} · ${symbol} · ${period} · KB API IVS11560 · ${rows.length}건`;history.replaceState(null,'',`?symbol=${symbol}&market=${$('market').value}&period=${period}`)}catch(error){rows=[];candles.setData([]);volumes.setData([]);$('candleRows').innerHTML='';message(error.message)}finally{$('load').disabled=false}}
  $('periods').addEventListener('click',e=>{const b=e.target.closest('button[data-period]');if(!b)return;period=b.dataset.period;$('periods').querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));load()});$('load').addEventListener('click',load);$('symbol').addEventListener('keydown',e=>{if(e.key==='Enter')load()});$('market').addEventListener('change',load);$('count').addEventListener('change',load);
  document.addEventListener('DOMContentLoaded',async()=>{const user=await initPage({requireAuth:true});if(!user)return;initChart();const q=new URLSearchParams(location.search);if(/^\d{6}$/.test(q.get('symbol')||''))$('symbol').value=q.get('symbol');if(['0','1'].includes(q.get('market')))$('market').value=q.get('market');if(['D','W','M','Y'].includes(q.get('period'))){period=q.get('period');$('periods').querySelectorAll('button').forEach(x=>x.classList.toggle('on',x.dataset.period===period))}load()});
})();
